language: node_js
node_js: "node"
git:
  depth: 3
before_script:
  - npm install chai
  - npm install mocha
  - npm install --save fake-dom
script:
  - ./node_modules/.bin/mocha --reporter spec --globals game
