language: node_js
node_js: "node"
git:
  depth: 3
before_script:
  - npm install chai
  - npm install -g mocha
  - npm install -g istanbul
  - npm install --save fake-dom
script:
  - mocha --reporter spec
  - istanbul cover mocha
